version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ../..
      dockerfile: ./docker/base/Dockerfile
    restart: unless-stopped
    command:
      - "-t"
      - ${BOT_TOKEN}
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  pg:
    container_name: pg
    image: postgres:14-alpine
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PSWD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/data/lib/postgresql/data/pgdata"
    volumes:
      - pg_data_volume:/data/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready --dbname=$DB_NAME --username=$DB_USER
      interval: 5s
      timeout: 5s
      retries: 10

  migrations:
    build:
      context: ../..
      dockerfile: ./docker/base/Dockerfile.migrations
    container_name: migrations
    depends_on:
      pg:
        condition: service_healthy
    environment:
      USER: ${DB_USER}
      PSWD: ${DB_PSWD}
      HOST: pg:5432
      DB: ${DB_NAME}

volumes:
  pg_data_volume: